
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClu2vBy0X6JDoEqA0wxIBTxu0-LqxDfO8',
    iosBundleId: 'com.alcantara',
    appId: '1:27406331071:ios:9060fd662084d2f86c6a0a',
    storageBucket: 'act4-6b5a1.appspot.com',
    messagingSenderId: '27406331071',
    iosClientId: 'undefined',
    projectId: 'act4-6b5a1'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtTVNQmYPwvx9pW9RdaEsJb6f7O_1WHxA',
    appId: '1:27406331071:android:5d71e140d3c5568e6c6a0a',
    messagingSenderId: '27406331071',
    projectId: 'act4-6b5a1',
    storageBucket: 'act4-6b5a1.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCArze0TSiPvHhiHBgF-tG1RfJnur3OmzQ',
    authDomain: 'act4-6b5a1.firebaseapp.com',
    projectId: 'act4-6b5a1',
    storageBucket: 'act4-6b5a1.appspot.com',
    messagingSenderId: '27406331071',
    appId: '1:27406331071:web:a43278cb009268cf6c6a0a'
  );
}
